baseURL = 'Glitchfix.github.io/'
languageCode = 'en-us'
title = 'Gltichfix'
theme = ["hugo-developer-portfolio"]

googleAnalytics = 'G-GPBS5WVPT5'

[params]
home = "Home" # What you want the homepage to show up as in the menu bar
# Meta data
description = "Shivanjan is a Software Engineer with intereset in AI, ML and robust backends. He also keeps interest in Hardwaare hacking and understanding the Linux kernel"
author = "Shivanjan Chakravorty"


  [params.contact]
#   formAction = "https://formspree.io/<Insert code>" # Add your formspree URL here to get emails

  # This contains the contact information for the footer
  [params.footer]
  email = "schakravorty846@gmail.com"
  address = "Bangalore, India"
#   googlemaps = "https://www.google.com/maps/embed/v1/place?q=place_id:ChIJwbHYJaUqfEgRK0Ui9dVGimc&key=AIzaSyAE_4rVAKux_DSPcb_OdSRDaovtPOSk_3U"

[params.plugins]
  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"
  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"

# navigation
[menu]
  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  weight=1


  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight=2

  [[menu.main]]
  name = "AI"
  URL = "ai"
  weight=3

  [[menu.main]]
  name = "About"
  URL = "about"
  weight=4

  # [[menu.main]]
  # name = "Contact"
  # URL = "contact"
  